os:
- linux
- windows
language: python
python:
- "3.9"

before_install:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python; fi

stages:
- lint
- test
- deploy
cache:
  pip: true
  
install:
- pip install --upgrade pip
- pip install poetry
- poetry install

jobs:
  include:
  - stage: lint
    script:
    - poetry run pylint appmap
    - poetry run vermin -t=3.5- appmap
    
  - stage: test
    python: "3.5"
    script:
    - poetry run tox
  - stage: test
    python: "3.6"
    script:
    - poetry run tox
  - stage: test
    python: "3.7"
    script:
    - poetry run tox
  - stage: test
    python: "3.8"
    script:
    - poetry run tox
  - stage: test
    python: "3.9"
    script:
    - poetry run tox

  - stage: deploy
    script: skip
    before_deploy:
    - awk -i inplace -v travis_tag=$TRAVIS_TAG '/# @@appmap-python-version@@/ {getline; printf("version = \"%s\"\n", travis_tag)}; !/version = "0.0.0"/ {print $0}' pyproject.toml
    # Note publishing this way requires the PyPI credentials to be
    # present in the environment. Travis doesn't currently support
    # providing environment variables to deploy providers through
    # the build config (i.e. in this file). So, they must be
    # provided through the build settings instead.
    deploy:
      # Don't undo the changes we just made to pyproject.toml
      skip_cleanup: true
      provider: script
      script: poetry publish --build
      on:
        tags: true
